/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "tim.h"
#include "gpio.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "usart.h"
#include "stdio.h"
#include "stdarg.h"
#include "stdint.h"
#include "string.h"

#include "ai_platform.h"
#include "ai_datatypes_defines.h"

#include "ai_platform_interface.h"
#include "ai_math_helpers.h"

#include "core_common.h"
#include "core_convert.h"

#include "layers.h"

#include "ch450.h"
#include "ch450_data.h"
#include "ch475.h"
#include "ch475_data.h"
#include "ch515.h"
#include "ch515_data.h"
#include "ch550.h"
#include "ch550_data.h"
#include "ch555.h"
#include "ch555_data.h"
#include "ch600.h"
#include "ch600_data.h"
#include "ch640.h"
#include "ch640_data.h"
#include "ch690.h"
#include "ch690_data.h"
#include "clf_rf.h"
#include "clf_rf_data.h"
#include "clf_svc.h"
#include "clf_svc_data.h"
#include "clf_xgb.h" // NOT generated by X-CUBE-AI

#include "test_data.h" // contains input_data_f
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
#define N_SAMPLES 315
#define N_CHANNELS 8
#define N_FUNC_GROUPS 3
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */
/* IO buffers ----------------------------------------------------------------*/
// for the calibration models
ai_float* data_ins[8] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};
ai_float* data_outs[8] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};

// for the classification models
AI_ALIGNED(32) ai_i8 ins_rf_1[AI_CLF_RF_IN_1_SIZE_BYTES];
AI_ALIGNED(32) ai_i8 ins_svc_1[AI_CLF_SVC_IN_1_SIZE_BYTES];
ai_i8* data_ins_rf[AI_CLF_RF_IN_NUM] = {ins_rf_1};
ai_i8* data_ins_svc[AI_CLF_SVC_IN_NUM] = {ins_svc_1};

AI_ALIGNED(4) ai_i8 outs_rf_1[AI_CLF_RF_OUT_1_SIZE_BYTES];
AI_ALIGNED(16) ai_i8 outs_rf_2[AI_CLF_RF_OUT_2_SIZE_BYTES];
ai_i8* data_outs_rf[AI_CLF_RF_OUT_NUM] = {outs_rf_1, outs_rf_2};

AI_ALIGNED(4) ai_i8 outs_svc_1[AI_CLF_SVC_OUT_1_SIZE_BYTES];
AI_ALIGNED(16) ai_i8 outs_svc_2[AI_CLF_SVC_OUT_2_SIZE_BYTES];
ai_i8* data_outs_svc[AI_CLF_SVC_OUT_NUM] = {outs_svc_1, outs_svc_2};

float data_outs_rf_float[N_FUNC_GROUPS];
float data_outs_svc_float[N_FUNC_GROUPS];
float data_outs_xgb_float[N_FUNC_GROUPS];

/* Activations buffers -------------------------------------------------------*/
AI_ALIGNED(32) uint8_t pool0[AI_CH450_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool1[AI_CH475_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool2[AI_CH515_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool3[AI_CH550_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool4[AI_CH555_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool5[AI_CH600_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool6[AI_CH640_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool7[AI_CH690_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool8[AI_CLF_RF_DATA_ACTIVATION_1_SIZE];
AI_ALIGNED(32) static uint8_t pool9[AI_CLF_SVC_DATA_ACTIVATION_1_SIZE];

ai_handle ch450_act_addr[] = {pool0};
ai_handle ch475_act_addr[] = {pool1};
ai_handle ch515_act_addr[] = {pool2};
ai_handle ch550_act_addr[] = {pool3};
ai_handle ch555_act_addr[] = {pool4};
ai_handle ch600_act_addr[] = {pool5};
ai_handle ch640_act_addr[] = {pool6};
ai_handle ch690_act_addr[] = {pool7};
ai_handle clf_rf_act_addr[] = {pool8};
ai_handle clf_svc_act_addr[] = {pool9};

/* AI objects ----------------------------------------------------------------*/

ai_handle ch450 = AI_HANDLE_NULL;
ai_handle ch475 = AI_HANDLE_NULL;
ai_handle ch515 = AI_HANDLE_NULL;
ai_handle ch550 = AI_HANDLE_NULL;
ai_handle ch555 = AI_HANDLE_NULL;
ai_handle ch600 = AI_HANDLE_NULL;
ai_handle ch640 = AI_HANDLE_NULL;
ai_handle ch690 = AI_HANDLE_NULL;
ai_handle clf_rf = AI_HANDLE_NULL;
ai_handle clf_svc = AI_HANDLE_NULL;

ai_buffer* ai_input_ch450;
ai_buffer* ai_output_ch450;
ai_buffer* ai_input_ch475;
ai_buffer* ai_output_ch475;
ai_buffer* ai_input_ch515;
ai_buffer* ai_output_ch515;
ai_buffer* ai_input_ch550;
ai_buffer* ai_output_ch550;
ai_buffer* ai_input_ch555;
ai_buffer* ai_output_ch555;
ai_buffer* ai_input_ch600;
ai_buffer* ai_output_ch600;
ai_buffer* ai_input_ch640;
ai_buffer* ai_output_ch640;
ai_buffer* ai_input_ch690;
ai_buffer* ai_output_ch690;
ai_buffer* ai_input_clf_rf;
ai_buffer* ai_output_clf_rf;
ai_buffer* ai_input_clf_svc;
ai_buffer* ai_output_clf_svc;

/* Program variables ---------------------------------------------------------*/

uint64_t runtimes_calib_sum[8] = {0, 0, 0, 0, 0, 0, 0, 0};
float runtimes_calib_avg[8] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
uint64_t runtimes_clf_sum[3] = {0, 0, 0};
float runtimes_clf_avg[3] = {0.0, 0.0, 0.0};
uint64_t runtimes_ALL_sum = 0;
float runtimes_ALL = 0.0;

ai_i32 batch;
ai_error ai_err;
uint32_t timestamp;
uint32_t OVERALL_start;
uint32_t elapsed;
// float uncalib_spectrum[8];
// float calib_spectrum[8];
int func_group;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */
/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_TIM11_Init();
  /* USER CODE BEGIN 2 */
  MX_USART2_UART_Init();
  UART_printf("\r\nValidation --  Calibration and Classifier Models\r\n\n");

  ai_bootstrap();
  if (ai_err.type != AI_ERROR_NONE) {
    ai_log_err(ai_err, "ai_bootstrap()");
  }


  // print header
  UART_printf("450nm,475nm,515nm,550nm,555nm,600nm,640nm,690nm,rf,svc,xgb\r\n");
  for (int i=0; i < N_SAMPLES; i++) {
    htim11.Instance->CNT = 0;
	HAL_TIM_Base_Start(&htim11);
    OVERALL_start = htim11.Instance->CNT;
    get_data(i);
    ai_run_calib();
    ai_run_clf();
    elapsed = htim11.Instance->CNT - OVERALL_start;
    if (OVERALL_start >  htim11.Instance->CNT) { 
      elapsed = OVERALL_start - (65535 - elapsed); 
    }
    runtimes_ALL_sum += elapsed;

    HAL_TIM_Base_Stop(&htim11);
    

    // print results
     for (int n=0; n < N_CHANNELS; n++) {
       UART_printf("%.10f,", *data_outs[n]);
     }
     UART_printf("%u,", get_category(data_outs_rf_float));
     UART_printf("%u,", get_category(data_outs_svc_float));
     UART_printf("%u\r\n", get_category(data_outs_xgb_float));
  }

  // process runtimes
  for (int i=0; i < N_CHANNELS; i++) {
    runtimes_calib_avg[i] = ((float)runtimes_calib_sum[i])/N_SAMPLES;
  }
  for (int i=0; i < 3; i++) {
    runtimes_clf_avg[i] = ((float)runtimes_clf_sum[i])/N_SAMPLES;
  }
  runtimes_ALL = ((float)runtimes_ALL_sum)/N_SAMPLES;

  UART_printf("\r\nDONE. Average runtimes:\r\n");
  UART_printf("  450nm: %.2f usec\r\n", runtimes_calib_avg[0]);
  UART_printf("  475nm: %.2f usec\r\n", runtimes_calib_avg[1]);
  UART_printf("  515nm: %.2f usec\r\n", runtimes_calib_avg[2]);
  UART_printf("  550nm: %.2f usec\r\n", runtimes_calib_avg[3]);
  UART_printf("  555nm: %.2f usec\r\n", runtimes_calib_avg[4]);
  UART_printf("  600nm: %.2f usec\r\n", runtimes_calib_avg[5]);
  UART_printf("  640nm: %.2f usec\r\n", runtimes_calib_avg[6]);
  UART_printf("  690nm: %.2f usec\r\n", runtimes_calib_avg[7]);
  UART_printf("     RF: %.2f usec\r\n", runtimes_clf_avg[0]);
  UART_printf("    SVC: %.2f usec\r\n", runtimes_clf_avg[1]);
  UART_printf("    XGB: %.2f usec\r\n", runtimes_clf_avg[2]);
  UART_printf("OVERALL: %.2f usec\r\n", runtimes_ALL);

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 8;
  RCC_OscInitStruct.PLL.PLLN = 100;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = 7;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */
void UART_printf(char *format, ...) {
	char buffer[256];
	va_list args;
	va_start(args, format);
	vsnprintf(buffer, sizeof(buffer), format, args);
	va_end(args);
	HAL_UART_Transmit(&huart2, (uint8_t *)buffer, strlen(buffer), 1000);
}

void ai_log_err(ai_error err, char *fct)
{
  if (fct)
    UART_printf("AI Error (%s) - type=0x%02x code=0x%02x\r\n", fct,
        err.type, err.code);
  else
    UART_printf("AI Error - type=0x%02x code=0x%02x\r\n", err.type, err.code);

  do {} while (1);
}

int ai_bootstrap(void) {
  UART_printf("Executing ai_bootstrap()\r\n");

  char* err_msg;
  ai_err = ai_ch450_create_and_init(&ch450, ch450_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_ch450_create_and_init";}
  ai_err = ai_ch475_create_and_init(&ch475, ch475_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_ch475_create_and_init";}
  ai_err = ai_ch515_create_and_init(&ch515, ch515_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_ch515_create_and_init";}
  ai_err = ai_ch550_create_and_init(&ch550, ch550_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_ch550_create_and_init";}
  ai_err = ai_ch555_create_and_init(&ch555, ch555_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_ch555_create_and_init";}
  ai_err = ai_ch600_create_and_init(&ch600, ch600_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_ch600_create_and_init";}
  ai_err = ai_ch640_create_and_init(&ch640, ch640_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_ch640_create_and_init";}
  ai_err = ai_ch690_create_and_init(&ch690, ch690_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_ch690_create_and_init";}
  ai_err = ai_clf_rf_create_and_init(&clf_rf, clf_rf_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_clf_rf_create_and_init";}
  ai_err = ai_clf_svc_create_and_init(&clf_svc, clf_svc_act_addr, NULL);
  if (ai_err.type != AI_ERROR_NONE) {err_msg = "ai_clf_svc_create_and_init";}

  if (ai_err.type != AI_ERROR_NONE) {
    UART_printf("1. (FAIL) Creation of model instances\r\n");
    ai_log_err(ai_err, err_msg);
    return -1;
  } else {
	  // UART_printf("1. (SUMAKSES) Creation of ALL model instances\r\n");
  }

  ai_input_ch450 = ai_ch450_inputs_get(ch450, NULL);
  ai_output_ch450 = ai_ch450_outputs_get(ch450, NULL);
  ai_input_ch475 = ai_ch475_inputs_get(ch475, NULL);
  ai_output_ch475 = ai_ch475_outputs_get(ch475, NULL);
  ai_input_ch515 = ai_ch515_inputs_get(ch515, NULL);
  ai_output_ch515 = ai_ch515_outputs_get(ch515, NULL);
  ai_input_ch550 = ai_ch550_inputs_get(ch550, NULL);
  ai_output_ch550 = ai_ch550_outputs_get(ch550, NULL);
  ai_input_ch555 = ai_ch555_inputs_get(ch555, NULL);
  ai_output_ch555 = ai_ch555_outputs_get(ch555, NULL);
  ai_input_ch600 = ai_ch600_inputs_get(ch600, NULL);
  ai_output_ch600 = ai_ch600_outputs_get(ch600, NULL);
  ai_input_ch640 = ai_ch640_inputs_get(ch640, NULL);
  ai_output_ch640 = ai_ch640_outputs_get(ch640, NULL);
  ai_input_ch690 = ai_ch690_inputs_get(ch690, NULL);
  ai_output_ch690 = ai_ch690_outputs_get(ch690, NULL);
  ai_input_clf_rf = ai_clf_rf_inputs_get(clf_rf, NULL);
  ai_output_clf_rf = ai_clf_rf_outputs_get(clf_rf, NULL);
  ai_input_clf_svc = ai_clf_svc_inputs_get(clf_svc, NULL);
  ai_output_clf_svc = ai_clf_svc_outputs_get(clf_svc, NULL);

  // UART_printf("2. (SUMAKSES) Allocating input & output data storage\r\n");

  data_ins[0] = (*ai_input_ch450).data;
  data_outs[0] = (*ai_output_ch450).data;
  data_ins[1] = (*ai_input_ch475).data;
  data_outs[1] = (*ai_output_ch475).data;
  data_ins[2] = (*ai_input_ch515).data;
  data_outs[2] = (*ai_output_ch515).data;
  data_ins[3] = (*ai_input_ch550).data;
  data_outs[3] = (*ai_output_ch550).data;
  data_ins[4] = (*ai_input_ch555).data;
  data_outs[4] = (*ai_output_ch555).data;
  data_ins[5] = (*ai_input_ch600).data;
  data_outs[5] = (*ai_output_ch600).data;
  data_ins[6] = (*ai_input_ch640).data;
  data_outs[6] = (*ai_output_ch640).data;
  data_ins[7] = (*ai_input_ch690).data;
  data_outs[7] = (*ai_output_ch690).data;
  data_ins_rf[0] = ai_input_clf_rf[0].data;
  data_ins_svc[0] = ai_input_clf_svc[0].data;
  ai_output_clf_rf[0].data = AI_HANDLE_PTR(data_outs_rf[0]);
  ai_output_clf_rf[1].data = AI_HANDLE_PTR(data_outs_rf[1]);
  ai_output_clf_svc[0].data = AI_HANDLE_PTR(data_outs_svc[0]);
  ai_output_clf_svc[1].data = AI_HANDLE_PTR(data_outs_svc[1]);

  // UART_printf("3. (SUMAKSES) Pointing of global variables to model in/out buffers\r\n");
  // UART_printf("End of ai_bootstrap()\r\n\n");

  return 0;
}

int get_data(int idx) {
  if (idx > N_SAMPLES-1) {
    UART_printf("\r\nERROR: Index out of bounds. Please input index < 315\r\n");
    return -1;
  }
  for (int i=0; i < N_CHANNELS; i++) {
    *data_ins[i] = (ai_float) input_data_f[(idx*8) + i];
  }

  return 0;
}

int ai_run_calib(void) {
  // UART_printf("Running Calibration models\r\n");
  char* err_msg = "";

  // HAL_TIM_Base_Start(&htim11);
  // uint32_t time_start = htim11.Instance->CNT;

  timestamp = htim11.Instance->CNT;
  batch = ai_ch450_run(ch450, ai_input_ch450, ai_output_ch450);
  runtimes_calib_sum[0] += htim11.Instance->CNT - timestamp;
  if (batch <= 0) { err_msg = "ai_ch450_run"; }

  timestamp = htim11.Instance->CNT;
  batch = ai_ch475_run(ch475, ai_input_ch475, ai_output_ch475);
  runtimes_calib_sum[1] += htim11.Instance->CNT - timestamp;
  if (batch <= 0) { err_msg = "ai_ch475_run"; }

  timestamp = htim11.Instance->CNT;
  batch = ai_ch515_run(ch450, ai_input_ch515, ai_output_ch515);
  runtimes_calib_sum[2] += htim11.Instance->CNT - timestamp;
  if (batch <= 0) { err_msg = "ai_ch515_run"; }

  timestamp = htim11.Instance->CNT;
  batch = ai_ch550_run(ch450, ai_input_ch550, ai_output_ch550);
  runtimes_calib_sum[3] += htim11.Instance->CNT - timestamp;
  if (batch <= 0) { err_msg = "ai_ch550_run"; }

  timestamp = htim11.Instance->CNT;
  batch = ai_ch555_run(ch450, ai_input_ch555, ai_output_ch555);
  runtimes_calib_sum[4] += htim11.Instance->CNT - timestamp;
  if (batch <= 0) { err_msg = "ai_ch555_run"; }

  timestamp = htim11.Instance->CNT;
  batch = ai_ch600_run(ch450, ai_input_ch600, ai_output_ch600);
  runtimes_calib_sum[5] += htim11.Instance->CNT - timestamp;
  if (batch <= 0) { err_msg = "ai_ch600_run"; }

  timestamp = htim11.Instance->CNT;
  batch = ai_ch640_run(ch450, ai_input_ch640, ai_output_ch640);
  runtimes_calib_sum[6] += htim11.Instance->CNT - timestamp;
  if (batch <= 0) { err_msg = "ai_ch640_run"; }

  timestamp = htim11.Instance->CNT;
  batch = ai_ch690_run(ch450, ai_input_ch690, ai_output_ch690);
  runtimes_calib_sum[7] += htim11.Instance->CNT - timestamp;
  if (batch <= 0) { err_msg = "ai_ch690_run"; }

  // elapsed = htim11.Instance->CNT - time_start;
//  HAL_TIM_Base_Stop(&htim11);
  if (strlen(err_msg) > 1) {
    UART_printf("1. (FAIL) Calibration model/s failed :((\r\n");
    UART_printf("Failure at %s\r\n", err_msg);
    return -1;
  }
  
  // UART_printf("1. (SUMAKSES) Calibration successful (TIME: %i microseconds)\r\n", elapsed);
  // UART_printf("idx        input       output   time\r\n");
  // for (int i=0; i < N_CHANNELS; i++) {
  //   UART_printf(" %i  %.10f %.10f %4ius\r\n", i, *data_ins[i], *data_outs[i], runtimes_calib_sum[i]);
  // }

  return 0;
}

int ai_run_clf(void) {

//  HAL_TIM_Base_Start(&htim11);
//  for (int i=0; i < N_CHANNELS; i++) {
//	((float*)data_ins_rf)[i] = *data_outs[i];
//	((float*)data_ins_svc)[i] = *data_outs[i];
//  }
  memcpy(data_ins_rf[0], data_outs[0], 32);
  memcpy(data_ins_svc[0], data_outs[0], 32);

  timestamp = htim11.Instance->CNT;
  batch = ai_clf_rf_run(clf_rf, ai_input_clf_rf, ai_output_clf_rf);
  elapsed = htim11.Instance->CNT - timestamp;
  if (timestamp >  htim11.Instance->CNT) { 
    elapsed = timestamp - (65535 - elapsed); 
  }
  runtimes_clf_sum[0] += elapsed;
  if (batch <= 0) {
    UART_printf("RF Classification inference failed :((\r\n");
    ai_log_err(ai_clf_rf_get_error(clf_rf), "ai_clf_rf_run");
  }

  memcpy(&data_outs_rf_float[0], data_outs_rf[1], 4);
  memcpy(&data_outs_rf_float[1], data_outs_rf[1]+4, 4);
  memcpy(&data_outs_rf_float[2], data_outs_rf[1]+8, 4);
  // UART_printf("Output 2: %.10f %.10f %.10f\r\n", data_outs_rf_float[0], data_outs_rf_float[1], data_outs_rf_float[2]);
  // UART_printf("Func Grp: %u\r\n", get_category(data_outs_rf_float));

  timestamp = htim11.Instance->CNT;
  batch = ai_clf_svc_run(clf_svc, ai_input_clf_svc, ai_output_clf_svc);
  elapsed = htim11.Instance->CNT - timestamp;
  if (timestamp >  htim11.Instance->CNT) { 
    elapsed = timestamp - (65535 - elapsed); 
  }
  runtimes_clf_sum[1] += elapsed;
  if (batch <= 0) {
    UART_printf("SVC Classification inference failed :((\r\n");
    ai_log_err(ai_clf_svc_get_error(clf_svc), "ai_clf_svc_run");
  }

  memcpy(&data_outs_svc_float[0], data_outs_rf[1], 4);
  memcpy(&data_outs_svc_float[1], data_outs_rf[1]+4, 4);
  memcpy(&data_outs_svc_float[2], data_outs_rf[1]+8, 4);
  // UART_printf("Output 2: %.10f %.10f %.10f\r\n", data_outs_svc_float[0], data_outs_svc_float[1], data_outs_svc_float[2]);
  // UART_printf("Func Grp: %u\r\n", get_category(data_outs_svc_float));

  timestamp = htim11.Instance->CNT;
  ai_clf_xgb_run((float*)data_outs[0], &data_outs_xgb_float[0]);
  elapsed = htim11.Instance->CNT - timestamp;
  if (timestamp >  htim11.Instance->CNT) { 
    elapsed = timestamp - (65535 - elapsed); 
  }
  runtimes_clf_sum[2] += elapsed;
  // UART_printf("(SUMAKSES) XGB Classification successful. (TIME: %u)\r\n", elapsed);
  // UART_printf("Output 2: %.10f %.10f %.10f\r\n", data_outs_xgb_float[0], data_outs_xgb_float[1], data_outs_xgb_float[2]);
  // UART_printf("Func Grp: %u\r\n", get_category(data_outs_xgb_float));

  return 0;
}

int get_category(float model_output[N_FUNC_GROUPS]) {
  float max = model_output[0];
  int max_idx = 0;

  for (int i=0; i < N_FUNC_GROUPS; i++) {
    if (model_output[i] > max) {
      max = model_output[i];
      max_idx = i;
    }
  }

  return max_idx;
}

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
